### PR TITLE
HT-1460 Institutions table: show how many people with access by insti…

### PR DESCRIPTION
**Pull request by moseshll**
…tution

Opting for the simpler approach of displaying this info on the institution show page.

### CODE REVIEW

**Review by aelkiss — APPROVED** [review]
Nice. Do we want to also actually show the users (or have a link to the user page with an appropriate filter?)

**Comment by moseshll** [comment]
My feeling is that this is meant to be zero/not-zero sanity check on the counts. Given that the index page is sortable and searchable by institution I'd say the information need not be further elaborated upon (for now).

**Comment by aelkiss** [comment]
:+1:

**Comment by aelkiss** [comment]
:+1:

**Pull request merged**
