### PR TITLE
HT-3261 Update OTIS dependencies

### PR DESCRIPTION
**Pull request by moseshll**
- Use Ruby 3.0.3 and Rails 6.1
- Use latest Keycard to pick up double-splat fixes
- Fix a compatibility issue with our Bootstrap/SASS setup by not deriving CSS classes from former.
- Update some code formatting for the benefit of `standardrb`

### CODE REVIEW

**Review by aelkiss — APPROVED** [review]
Looks great. Glad to see we needed basically no changes to update to Rails 6.

**Comment by moseshll** [comment]
Wanna go for Rails 7?

**Comment by aelkiss** [comment]
Worth a try to see what breaks...

**Comment by moseshll** [comment]
Checkpoint breaks. Let's hold off on Rails 7 until that little "problem" is squared away.

**Pull request merged**
