### PR TITLE
DEV-438 update otis to use support@hathitrust.org

### PR DESCRIPTION
**Pull request by moseshll**
- Move support email to settings and interpolate into templates.
- Fix system test with Capybara ambiguous element error.

### CODE REVIEW

**Comment by moseshll** [comment]
@mwarin The Capybara error referenced above made me nervous so I'm requesting a sanity check review. I'd kinda like to see this pass the normal and the system tests (`docker-compose run test` and `docker-compose run system-test`) with no weirdness.

**Review by mwarin — COMMENTED** [review]
Would it be worth sticking the whole 
`<a href="<%= Otis.config.support_email %>"><%= Otis.config.support_email %></a>`
into a var, since you are using that more than a few times?

**Comment by mwarin** [comment]
`docker-compose run system-test` did not give any errors the first time I ran it, but the second time it threw a `ActionController::RoutingError`.

`docker-compose run test` ran fine, but I am seeing more than a few skipped tests (~20). I would recommend seeing if you could unskip or removing (some of) them?

**Comment by mwarin** [comment]
Actually, a test that github ran failed but, coveralls covered the exit code. 
https://github.com/hathitrust/otis/actions/runs/3185370830/jobs/5194870574#step:8:38

**Review by mwarin — APPROVED** [review]
I approve these changes, but acknowledge that other issues relating to the capybara tests where uncovered and should be dealt with separately.

**Pull request merged**
