### PR TITLE
HT-1529 integrate shib

### PR DESCRIPTION
**Pull request by moseshll**
Not sure about where the Shib settings should live, or how they need to be tweaked further.

The second commit has also been deployed on Staging.

### CODE REVIEW

**Comment by aelkiss** [comment]
Also, just for the future, note that the github / jira integration will only work if you include the full issue key e.g. HT-1529 in the commit messages / PR title / branch name.

**Comment by botimer** [comment]
@moseshll Hmm, yeah, it's odd to hear that the session is going away. I'd like to see that in action to understand what's happening and determine whether we need a keycard change.

**Comment by aelkiss** [comment]
I thought maybe this was just a side effect of hitting the FakeShibController, but it looks like it's happening even in with staging. See the branch https://github.com/hathitrust/otis/tree/regular-validate-session (currently deployed to staging).

Based on what I'm seeing in dev, I suspect a timestamp isn't getting added to the session when the session is reset, but I will take a closer look and see.

**Comment by aelkiss** [comment]
hmm... Now I'm unsure. It looks like Keycard's `setup_session` method should be preserving the `return_to` after coming back from login. I'll see if I can replicate in dev (with the additional caveat that FakeShibController also needs to preserve the `return_to`)

**Comment by aelkiss** [comment]
Hmmm so I think `SessionController#new` tries to validate the session (thereby whacking the `return_to`) before issuing the redirect to Shibboleth.

**Comment by botimer** [comment]
Yup... The session controllers are always sort of ring zero. `skip_before_action validate_session` is the right path.

**Pull request merged**
